status = warn
name = TaxCalculatorPropertiesConfig


appenders = console, file


appender.console.type = Console
appender.console.name = LogToConsole
appender.console.layout.type = PatternLayout
appender.console.layout.pattern = %d{yyyy-MM-dd HH:mm:ss.SSS} [%t] %-5level %logger{36} - %msg%n


appender.file.type = File
appender.file.name = LogToFile
appender.file.fileName = logs/tax-calculator.json
appender.file.layout.type = JsonTemplateLayout
appender.file.layout.eventTemplateUri = classpath:Log4j2-json-layout.json


rootLogger.level = info
rootLogger.appenderRef.console.ref = LogToConsole
rootLogger.appenderRef.file.ref = LogToFile

